### ISSUE TITLE
SSL Certificate validation errors on CentOS 6.

### ISSUE THREAD

**Issue by swalberg** [nationbuilder/nationbuilder-rb#35]
Everything was working great on my Mac until I tried to deploy to Linux:

```
irb(main):006:0> nb = NationBuilder::Client.new slug, token; nil
=> nil
irb(main):007:0> nb.call :people, :count
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `connect'
	from /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `ssl_connect'
	from /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:24:in `create_socket'
	from /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/session.rb:746:in `block in connect'
	from /home/campaign/.rubies/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
```

I suspect the problem is actually from HTTPClient:

```
$ ruby -r httpclient -e "puts  HTTPClient.new.get_content('https://ertw.nationbuilder.com')"
/home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
	from /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/ssl_socket.rb:46:in `ssl_connect'
```

My CA bundle is up to date, but it seems like HTTPClient doesn't use the system CAs. I can overwrite it:

```
 cp /etc/pki/tls/cert.pem /home/campaign/.gem/ruby/2.3.1/gems/httpclient-2.8.2.4/lib/httpclient/cacert.pem
```

And then it works:

```
irb(main):005:0> nb.call :people, :count
=> {"people_count"=>65, "status_code"=>200}
```

But it would be nice not to have to do that. Do you know of any workarounds?

By coincidence (and really, it is!) #31 would let us access the httpclient object and manually configure the SSL browser path:

```
client.ssl_config.add_trust_ca "/etc/pki/tls/cert.pem"
```

**Comment by swalberg** [comment]
This works now that I'm using the code from #31:

```Ruby
def nb
    http_client = HTTPClient.new
    http_client.ssl_config.add_trust_ca CA_BUNDLE_LOCATION if CA_BUNDLE_LOCATION
    NationBuilder::Client.new(nation_builder_slug, nation_builder_auth_token, retries: 8, http_client: http_client)
  end
```
